# Generated by Django 4.2 on 2023-05-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('purchase', '0002_alter_purchase_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='shop_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_items', to='shop.shopitems'),
        ),
    ]
