# Generated by Django 4.2 on 2023-05-21 08:32

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=500, unique=True, verbose_name='E-mail')),
                ('phone', phone_field.models.PhoneField(max_length=20, verbose_name='Номер телефона')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь пользоваться инфраструктурой Employee', verbose_name='Employee status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
