# Generated by Django 4.2 on 2023-05-27 22:27

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name_alter_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
