# Generated by Django 4.2 on 2023-05-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название обуви')),
                ('image_before', models.ImageField(upload_to='product', verbose_name='Изображение до')),
                ('image_after', models.ImageField(upload_to='product', verbose_name='Изображение после')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
            },
        ),
    ]
