# Generated by Django 4.2 on 2023-05-14 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='image_after',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='image_before',
        ),
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 5, 14, 7, 21, 44, 477775, tzinfo=datetime.timezone.utc), upload_to='product', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
