# Generated by Django 4.2 on 2023-05-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
        ('shop', '0002_shopitems_purchase'),
    ]

    operations = [
    ]
